export default [
  {
    path: "components/ui-elements/alert",
    name: "Alert",
    component: () => import("@/views/components/ui-elements/Alert.vue"),
    meta: {
      title: "Alert",
      icon: "alert-circle-outline",
      group: "Components",
      subgroup: "UI Elements",
    },
  },
  {
    path: "components/ui-elements/avatar",
    name: "Avatar",
    component: () => import("@/views/components/ui-elements/Avatar.vue"),
    meta: {
      title: "Avatar",
      icon: "person-circle-outline",
      group: "Components",
      subgroup: "UI Elements",
    },
  },
  {
    path: "components/ui-elements/badge",
    name: "Badge",
    component: () => import("@/views/components/ui-elements/Badge.vue"),
    meta: {
      title: "Badge",
      icon: "ribbon-outline",
      group: "Components",
      subgroup: "UI Elements",
    },
  },
  {
    path: "components/ui-elements/button",
    name: "Button",
    component: () => import("@/views/components/ui-elements/Button.vue"),
    meta: {
      title: "Button",
      icon: "radio-button-on-outline",
      group: "Components",
      subgroup: "UI Elements",
    },
  },
  {
    path: "components/ui-elements/modal",
    name: "Modal",
    component: () => import("@/views/components/ui-elements/Modal.vue"),
    meta: {
      title: "Modal",
      icon: "browsers-outline",
      group: "Components",
      subgroup: "UI Elements",
    },
  },
  {
    path: "components/ui-elements/list",
    name: "List",
    component: () => import("@/views/components/ui-elements/List.vue"),
    meta: {
      title: "List",
      icon: "list-outline",
      group: "Components",
      subgroup: "UI Elements",
    },
  },
  {
    path: "components/ui-elements/menu",
    name: "Menu",
    component: () => import("@/views/components/ui-elements/Menu.vue"),
    meta: {
      title: "Menu",
      icon: "menu-outline",
      group: "Components",
      subgroup: "UI Elements",
    },
  },
  {
    path: "components/ui-elements/pagination",
    name: "Pagination",
    component: () => import("@/views/components/ui-elements/Pagination.vue"),
    meta: {
      title: "Pagination",
      icon: "ellipsis-horizontal-outline",
      group: "Components",
      subgroup: "UI Elements",
    },
  },
  {
    path: "components/ui-elements/tabs",
    name: "Tabs",
    component: () => import("@/views/components/ui-elements/Tabs.vue"),
    meta: {
      title: "Tabs",
      icon: "albums-outline",
      group: "Components",
      subgroup: "UI Elements",
    },
  },
  {
    path: "components/ui-elements/timeline",
    name: "Timeline",
    component: () => import("@/views/components/ui-elements/Timeline.vue"),
    meta: {
      title: "Timeline",
      icon: "time-outline",
      group: "Components",
      subgroup: "UI Elements",
    },
  },
  {
    path: "components/ui-elements/tooltip",
    name: "Tooltip",
    component: () => import("@/views/components/ui-elements/Tooltip.vue"),
    meta: {
      title: "Tooltip",
      icon: "information-circle-outline",
      group: "Components",
      subgroup: "UI Elements",
    },
  },
  {
    path: "components/ui-elements/carousel",
    name: "Carousel",
    component: () => import("@/views/components/ui-elements/Carousel.vue"),
    meta: {
      title: "Carousel",
      icon: "albums-outline",
      group: "Components",
      subgroup: "UI Elements",
    },
  },
  {
    path: "components/ui-elements/collapse",
    name: "Collapse",
    component: () => import("@/views/components/ui-elements/Collapse.vue"),
    meta: {
      title: "Collapse",
      icon: "remove-outline",
      group: "Components",
      subgroup: "UI Elements",
    },
  },
  {
    path: "components/ui-elements/tag",
    name: "Tag",
    component: () => import("@/views/components/ui-elements/Tag.vue"),
    meta: {
      title: "Tag",
      icon: "ribbon-outline",
      group: "Components",
      subgroup: "UI Elements",
    },
  },
  {
    path: "components/tables/basic-table",
    name: "Basic-Table",
    component: () => import("@/views/components/tables/basic-table/index.vue"),
    meta: {
      title: "Basic Table",
      icon: "grid-outline",
      group: "Components",
      subgroup: "Tables",
    },
  },
  {
    path: "components/tables/data-table",
    name: "Data-Table",
    component: () => import("@/views/components/tables/data-table/index.vue"),
    meta: {
      title: "Data Table",
      icon: "list-outline",
      group: "Components",
      subgroup: "Tables",
    },
  },
  {
    path: "components/charts/line-chart",
    name: "Line-Chart",
    component: () => import("@/views/components/charts/line-chart/index.vue"),
    meta: {
      title: "Line Chart",
      icon: "analytics-outline",
      group: "Components",
      subgroup: "Charts",
    },
  },
  {
    path: "components/charts/bar-chart",
    name: "Bar-Chart",
    component: () => import("@/views/components/charts/bar-chart/index.vue"),
    meta: {
      title: "Bar Chart",
      icon: "bar-chart-outline",
      group: "Components",
      subgroup: "Charts",
    },
  },
  {
    path: "components/charts/pie-chart",
    name: "Pie-Chart",
    component: () => import("@/views/components/charts/pie-chart/index.vue"),
    meta: {
      title: "Pie Chart",
      icon: "pie-chart-outline",
      group: "Components",
      subgroup: "Charts",
    },
  },
  {
    path: "components/charts/mixed-chart",
    name: "Mixed-Chart",
    component: () => import("@/views/components/charts/mixed-chart/index.vue"),
    meta: {
      title: "Mixed Chart",
      icon: "layers-outline",
      group: "Components",
      subgroup: "Charts",
    },
  },
  {
    path: "components/typography",
    name: "Typography",
    component: () => import("@/views/components/typography/index.vue"),
    meta: { title: "Typography", icon: "text-outline", group: "Components" },
  },
  {
    path: "components/icons",
    name: "Icons",
    component: () => import("@/views/components/icons/index.vue"),
    meta: { title: "Icons", icon: "apps-outline", group: "Components" },
  },
  {
    path: "components/ui-elements/extra/divider",
    name: "Divider",
    component: () => import("@/views/components/extra/divider/index.vue"),
    meta: {
      title: "Divider",
      icon: "remove-outline",
      group: "Components",
      subgroup: "Extra",
    },
  },
  {
    path: "components/ui-elements/extra/ellipsis",
    name: "Ellipsis",
    component: () => import("@/views/components/extra/ellipsis/index.vue"),
    meta: {
      title: "Ellipsis",
      icon: "ellipsis-horizontal-outline",
      group: "Components",
      subgroup: "Extra",
    },
  },
  {
    path: "components/ui-elements/extra/gradient-text",
    name: "GradientText",
    component: () => import("@/views/components/extra/gradient-text/index.vue"),
    meta: {
      title: "Gradient Text",
      icon: "color-palette-outline",
      group: "Components",
      subgroup: "Extra",
    },
  },
  {
    path: "components/ui-elements/extra/page-header",
    name: "PageHeader",
    component: () => import("@/views/components/extra/page-header/index.vue"),
    meta: {
      title: "Page Header",
      icon: "document-text-outline",
      group: "Components",
      subgroup: "Extra",
    },
  },
  {
    path: "components/ui-elements/extra/watermark",
    name: "Watermark",
    component: () => import("@/views/components/extra/watermark/index.vue"),
    meta: {
      title: "Watermark",
      icon: "water-outline",
      group: "Components",
      subgroup: "Extra",
    },
  },
  {
    path: "components/ui-elements/extra/countdown",
    name: "CountDown",
    component: () => import("@/views/components/extra/count-down/index.vue"),
    meta: {
      title: "Countdown",
      icon: "timer-outline",
      group: "Components",
      subgroup: "Extra",
    },
  },
];
