export default [
  {
    path: "forms/form-elements/select",
    name: "Select",
    component: () => import("@/views/forms/form-elements/Select.vue"),
    meta: {
      title: "Select",
      icon: "checkbox-outline",
      group: "Components",
      subgroup: "Form Elements",
    },
  },
  {
    path: "forms/form-elements/input",
    name: "Input",
    component: () => import("@/views/forms/form-elements/Input.vue"),
    meta: {
      title: "Input",
      icon: "radio-button-off-outline",
      group: "Components",
      subgroup: "Form Elements",
    },
  },
  {
    path: "forms/form-elements/radio",
    name: "Radio",
    component: () => import("@/views/forms/form-elements/Radio.vue"),
    meta: {
      title: "Radio",
      icon: "radio-button-off-outline",
      group: "Components",
      subgroup: "Form Elements",
    },
  },
  {
    path: "forms/form-elements/switch",
    name: "Switch",
    component: () => import("@/views/forms/form-elements/Switch.vue"),
    meta: {
      title: "Switch",
      icon: "toggle-outline",
      group: "Components",
      subgroup: "Form Elements",
    },
  },
  {
    path: "forms/form-elements/slider",
    name: "Slider",
    component: () => import("@/views/forms/form-elements/Slider.vue"),
    meta: {
      title: "Slider",
      icon: "remove-outline",
      group: "Components",
      subgroup: "Form Elements",
    },
  },
  {
    path: "forms/form-elements/autocomplete",
    name: "AutoComplete",
    component: () => import("@/views/forms/form-elements/AutoComplete.vue"),
    meta: {
      title: "AutoComplete",
      icon: "radio-button-off-outline",
      group: "Components",
      subgroup: "Form Elements",
    },
  },
  {
    path: "forms/form-elements/checkbox",
    name: "Checkbox",
    component: () => import("@/views/forms/form-elements/Checkbox.vue"),
    meta: {
      title: "Checkbox",
      icon: "checkbox-outline",
      group: "Components",
      subgroup: "Form Elements",
    },
  },
  {
    path: "forms/form-elements/datepicker",
    name: "DatePicker",
    component: () => import("@/views/forms/form-elements/DatePicker.vue"),
    meta: {
      title: "DatePicker",
      icon: "radio-button-off-outline",
      group: "Components",
      subgroup: "Form Elements",
    },
  },
  {
    path: "forms/form-elements/upload",
    name: "Upload",
    component: () => import("@/views/forms/form-elements/Upload.vue"),
    meta: {
      title: "Upload",
      icon: "radio-button-off-outline",
      group: "Components",
      subgroup: "Form Elements",
    },
  },
  {
    path: "forms/extra/cascader",
    name: "Cascader",
    component: () => import("@/views/forms/extra/Cascader.vue"),
    meta: {
      title: "Cascader",
      icon: "radio-button-off-outline",
      group: "Components",
      subgroup: "Extra Form Elements",
    },
  },
  {
    path: "forms/extra/color-picker",
    name: "ColorPicker",
    component: () => import("@/views/forms/extra/ColorPicker.vue"),
    meta: {
      title: "Color Picker",
      icon: "checkbox-outline",
      group: "Components",
      subgroup: "Extra Form Elements",
    },
  },
  {
    path: "forms/extra/dynamic-input",
    name: "DynamicInput",
    component: () => import("@/views/forms/extra/DynamicInput.vue"),
    meta: {
      title: "Dynamic Input",
      icon: "radio-button-off-outline",
      group: "Components",
      subgroup: "Extra Form Elements",
    },
  },
  {
    path: "forms/extra/dynamic-tags",
    name: "DynamicTags",
    component: () => import("@/views/forms/extra/DynamicTags.vue"),
    meta: {
      title: "Dynamic Tags",
      icon: "radio-button-off-outline",
      group: "Components",
      subgroup: "Extra Form Elements",
    },
  },
  {
    path: "forms/extra/input-number",
    name: "InputNumber",
    component: () => import("@/views/forms/extra/InputNumber.vue"),
    meta: {
      title: "Input Number",
      icon: "checkbox-outline",
      group: "Components",
      subgroup: "Extra Form Elements",
    },
  },
  {
    path: "forms/extra/input-otp",
    name: "InputOtp",
    component: () => import("@/views/forms/extra/InputOtp.vue"),
    meta: {
      title: "Input OTP",
      icon: "radio-button-off-outline",
      group: "Components",
      subgroup: "Extra Form Elements",
    },
  },
  {
    path: "forms/extra/mention",
    name: "Mention",
    component: () => import("@/views/forms/extra/Mention.vue"),
    meta: {
      title: "Mention",
      icon: "checkbox-outline",
      group: "Components",
      subgroup: "Extra Form Elements",
    },
  },
  {
    path: "forms/extra/rate",
    name: "Rate",
    component: () => import("@/views/forms/extra/Rate.vue"),
    meta: {
      title: "Rate",
      icon: "radio-button-off-outline",
      group: "Components",
      subgroup: "Extra Form Elements",
    },
  },
  {
    path: "forms/extra/transfer",
    name: "Transfer",
    component: () => import("@/views/forms/extra/Transfer.vue"),
    meta: {
      title: "Transfer",
      icon: "radio-button-off-outline",
      group: "Components",
      subgroup: "Extra Form Elements",
    },
  },
  {
    path: "forms/extra/tree-select",
    name: "TreeSelect",
    component: () => import("@/views/forms/extra/TreeSelect.vue"),
    meta: {
      title: "Tree Select",
      icon: "radio-button-off-outline",
      group: "Components",
      subgroup: "Extra Form Elements",
    },
  },
  {
    path: "forms/form-validation",
    name: "Form-Validation",
    component: () => import("@/views/forms/Form-Validation.vue"),
    meta: {
      title: "Form Validation",
      icon: "checkmark-outline",
      group: "Components",
    },
  },
  {
    path: "forms/form-wizard",
    name: "Form-Wizard",
    component: () => import("@/views/forms/Form-Wizard.vue"),
    meta: {
      title: "Form Wizard",
      icon: "chevron-forward-outline",
      group: "Components",
    },
  },
  {
    path: "forms/form-editor",
    name: "Form-Editor",
    component: () => import("@/views/forms/Form-Editor.vue"),
    meta: { title: "Form Editor", icon: "create-outline", group: "Components" },
  },
];
