export const PRODUCTS_LIST = [
  {
    id: 1,
    name: "Wireless Headphones Pro",
    category: "Electronics",
    price: 299.99,
    salePrice: 249.99,
    stock: 45,
    image: "https://picsum.photos/seed/headphones/300/200.jpg",
    description: "Premium wireless headphones with noise cancellation",
    isNew: true,
    isOnSale: true,
    status: "active",
    createdAt: "2024-01-10",
  },
  {
    id: 2,
    name: "Smart Watch Ultra",
    category: "Electronics",
    price: 499.99,
    stock: 12,
    image: "https://picsum.photos/seed/smartwatch/300/200.jpg",
    description: "Advanced fitness tracking and health monitoring",
    isNew: false,
    isOnSale: false,
    status: "active",
    createdAt: "2024-01-08",
  },
  {
    id: 3,
    name: "Organic Cotton T-Shirt",
    category: "Clothing",
    price: 29.99,
    stock: 0,
    image: "https://picsum.photos/seed/tshirt/300/200.jpg",
    description: "Comfortable and sustainable organic cotton",
    isNew: false,
    isOnSale: false,
    status: "out_of_stock",
    createdAt: "2024-01-05",
  },
  {
    id: 4,
    name: "JavaScript Guide Book",
    category: "Books",
    price: 39.99,
    salePrice: 29.99,
    stock: 120,
    image: "https://picsum.photos/seed/jsbook/300/200.jpg",
    description: "Complete guide to modern JavaScript development",
    isNew: true,
    isOnSale: true,
    status: "active",
    createdAt: "2024-01-12",
  },
  {
    id: 5,
    name: "Yoga Mat Premium",
    category: "Sports",
    price: 79.99,
    stock: 67,
    image: "https://picsum.photos/seed/yogamat/300/200.jpg",
    description: "Non-slip premium yoga mat with carrying strap",
    isNew: false,
    isOnSale: false,
    status: "active",
    createdAt: "2024-01-03",
  },
];

export const FORM_RULES = {
  name: { required: true, message: "Product name is required" },
  category: { required: true, message: "Category is required" },
  price: {
    required: true,
    type: "number",
    min: 0,
    message: "Price must be positive",
  },
  stock: {
    required: true,
    type: "number",
    min: 0,
    message: "Stock must be positive",
  },
};
